### ISSUE TITLE
ast2txt: Compare, keyword and While bugs

### ISSUE THREAD

**Issue by benjaminpjones** [Lautzoballsoup/ALife#10]
Compare: there can be multiple comparators/operations (i.e. var0 < var1 < var3)
    - Currently, ast2txt will output "{} < {} , {}" which is not functionally equivalent to "{} < {} < {}"
    - instead of looking at just op[0] we need to look at all ops for cases like: "var0 < var1 <= var2" where different operations are used.  and comma_separated is not the right tool for the comparators

keyword:  I believe these are used in function calls (sometimes by called "named parameters").  The keyword arguments have syntax similar to assignment, so it should be "{arg}={value}" instead of just arg.

While: This just needs a dedent at the end.

**Comment by Lautzoballsoup** [comment]
Fixed by [commit 0dd66ac](https://github.com/Lautzoballsoup/ALife/commit/0dd66acbb904c49b55d9264a6ad2a94704059947)
