### ISSUE TITLE
Support automatically converting code to an AST

### ISSUE THREAD

**Issue by Lautzoballsoup** [Lautzoballsoup/ALife#9]
ast2txt covers all cases except If statements and Try/Except statements. Once those are done, the code can be fully examined, debugged, and tweaked.

**Comment by Lautzoballsoup** [comment]
If and Try/Except covered by [commit 7e5caf0](https://github.com/Lautzoballsoup/ALife/commit/7e5caf033e0eded35042047a1764afa74fac20c6).

Splices aren't handled correctly when the lower or upper bound is null - ast2string chokes on list_a[:-1], for instance.

**Comment by benjaminpjones** [comment]
Null was fixed by having ast2txt(None) output '\n'

**Comment by Lautzoballsoup** [comment]
Fixed by Ben's work - this can be closed.
